name: Prepare Rust toolchain
description: "Download and register Rust compiler toolchain."

inputs:
  cookie:
    description: "Cookie for download authorization."
    required: true

runs:
  using: "composite"
  steps:
    - name: Restore Rust compiler toolchain cache
      id: rust-cache
      uses: actions/cache@v4
      with:
        path: rust
        key: ${{ runner.os }}-rust

    - name: Download Rust compiler toolchain if not cached
      if: steps.rust-cache.outputs.cache-hit != 'true'
      run: |
        curl --fail -L \
             --cookie "authorized_cookie=${{ inputs.cookie }}" \
             -o rust.tar.xz \
             'https://file.zyma.me/rust-081124.tar.xz'
      shell: bash

    - name: Decompress Rust compiler toolchain
      if: steps.rust-cache.outputs.cache-hit != 'true'
      run: tar -xf rust.tar.xz
      shell: bash

    - name: Register Rust compiler toolchain
      run: rustup toolchain link segstk-rust rust
      shell: bash
