name: Run Tests for Interrupt Unwinding

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test simple
        uses: ./.github/workflows/actions/run-test
        with:
          cookie: ${{ secrets.cookie }}
          category: interrupt
          sub-category: unwind
          test-name: simple
          timeout: 15s
