name: Run Tests for Mutex

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always

jobs:
  basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test basic
        uses: ./.github/workflows/actions/run-test
        with:
          category: sync
          sub-category: mutex
          test-name: basic

  stress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test stress
        uses: ./.github/workflows/actions/run-test
        with:
          category: sync
          sub-category: mutex
          test-name: stress

  priority:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test priority
        uses: ./.github/workflows/actions/run-test
        with:
          category: sync
          sub-category: mutex
          test-name: priority

  poison:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test poison
        uses: ./.github/workflows/actions/run-test
        with:
          category: sync
          sub-category: mutex
          test-name: poison

  priority_inversion:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run test priority_inversion
        uses: ./.github/workflows/actions/run-test
        with:
          category: sync
          sub-category: mutex
          test-name: priority_inversion
