name: All Test Cases

on:
  workflow_call:
    secrets:
      cookie:
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  sync:
    uses: ./.github/workflows/sync.yaml
    secrets:
      cookie: ${{ secrets.cookie }}

  task:
    uses: ./.github/workflows/task.yaml
    secrets:
      cookie: ${{ secrets.cookie }}

  interrupt:
    uses: ./.github/workflows/interrupt.yaml
    secrets:
      cookie: ${{ secrets.cookie }}

  debug:
    uses: ./.github/workflows/debug.yaml
    secrets:
      cookie: ${{ secrets.cookie }}
